In [94]:
import numpy as np

def Input_mnist(P=10):
    import numpy as np
    from keras.datasets import mnist
    # loading
    (X, y), (k,h) = mnist.load_data()
    # Define patterns
    M = np.zeros((P,28*28))
    l    = 0
    flag = 0
    for i in range(0,P):
        for j in range(np.size(y)):
            if y[j] == i:
                if flag == 0:
                    m = j
                    M[l,:] = np.ravel(X[j,:,:]) 
                    flag = 1
                    l += 1
        flag = 0
    for i in range(0,P):
        M[i] /= np.max(M[i])
    mask = M<=0.5
    M[mask] = -1
    M[~mask] = 1
    return M

In [2]:
import numpy as np

def J(M):
    
    matrix_dim=M.shape
    J=np.zeros((matrix_dim[1],matrix_dim[1]))

    for i in range(0,matrix_dim[1]):
        for j in range(0,matrix_dim[1]):
            if j!=i:
                J[i,j]=np.sum([M[a,i]*M[a,j] for a in range(0,matrix_dim[0])])/matrix_dim[1]
    return J

In [3]:
def Wrong_patterns(q,M):
    from numpy import random

    Y=np.zeros((M.shape))

    for i in range(0,M.shape[0]):
        x=M[i,:]

        rand=np.random.random_sample()
        for j in range(0,M.shape[1]):
            rand=np.random.random_sample()
            if rand<=q:
                Y[i,j]=x[j]
            else:
                Y[i,j]=-x[j]
    return Y

In [106]:
def update_y(J,y,M,iter_max=100):
    import numpy as np
    flag = 1
    t    = 0 
    
    # Update
    y_old    = np.zeros(len(y))
    y_old[:] = y[:]
    while(flag and t <= iter_max):
        for i in range(0,J.shape[1]):
            y[i] = np.sign(np.dot(J[i,:],y))
            if (y[i]==0):
                y[i] = 1
        t += 1
        k = 0
        for j in range(0,len(y)):
            if(y[j] == y_old[j]):
                k += 1
        if k==len(y):
            flag = 0
        else:
            y_old[:] = y[:]
                
    # Pattern of y updated
    P_a = -1
    if (flag == 0):
        for i in range(0,M.shape[0]):
            k = 0
            for j in range(0,len(y)):
                if(y[j] == M[i,j]):
                    k += 1
            if k == len(y):
                P_a = i
#     print("Final y:")
#     print(y)
    return P_a,t

In [5]:
# def J_nn(M):
    
#     matrix_dim=M.shape
#     J=np.zeros((matrix_dim[1],matrix_dim[1]))
    
#     for i in range(0,matrix_dim[1]):
#         for j in range(0,matrix_dim[1]):
#             if j!=i:
#                 J[i,j]=np.sum([M[a,i]*M[a,j] for a in range(0,matrix_dim[0])])/matrix_dim[1]
#     return J

In [95]:
M=Input_mnist(2)
J_matrix=J(M)

print('patterns:',M, 'shape:', M.shape)
print('J: ', J_matrix)

patterns: [[-1. -1. -1. ... -1. -1. -1.]
 [-1. -1. -1. ... -1. -1. -1.]] shape: (2, 784)
J:  [[0.         0.00255102 0.00255102 ... 0.00255102 0.00255102 0.00255102]
 [0.00255102 0.         0.00255102 ... 0.00255102 0.00255102 0.00255102]
 [0.00255102 0.00255102 0.         ... 0.00255102 0.00255102 0.00255102]
 ...
 [0.00255102 0.00255102 0.00255102 ... 0.         0.00255102 0.00255102]
 [0.00255102 0.00255102 0.00255102 ... 0.00255102 0.         0.00255102]
 [0.00255102 0.00255102 0.00255102 ... 0.00255102 0.00255102 0.        ]]


In [242]:
Y_bu=Wrong_patterns(0.5,M)
#print(Y_bu[0])
pattern_giust, iterazione= update_y(J_matrix,Y_bu[0,:],M)
print(pattern_giust,iterazione)

-1 2


In [171]:
np.random.random_sample()

0.566563196594316